# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import test_pb2 as test__pb2


class FTQueueStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.qCreate = channel.unary_unary(
        '/FTQueue/qCreate',
        request_serializer=test__pb2.label.SerializeToString,
        response_deserializer=test__pb2.queueid.FromString,
        )
    self.qPush = channel.unary_unary(
        '/FTQueue/qPush',
        request_serializer=test__pb2.Push_message.SerializeToString,
        response_deserializer=test__pb2.void.FromString,
        )
    self.qId = channel.unary_unary(
        '/FTQueue/qId',
        request_serializer=test__pb2.label.SerializeToString,
        response_deserializer=test__pb2.queueid.FromString,
        )
    self.qPop = channel.unary_unary(
        '/FTQueue/qPop',
        request_serializer=test__pb2.queueid.SerializeToString,
        response_deserializer=test__pb2.Item.FromString,
        )
    self.qTop = channel.unary_unary(
        '/FTQueue/qTop',
        request_serializer=test__pb2.queueid.SerializeToString,
        response_deserializer=test__pb2.Item.FromString,
        )
    self.qSize = channel.unary_unary(
        '/FTQueue/qSize',
        request_serializer=test__pb2.queueid.SerializeToString,
        response_deserializer=test__pb2.QueLength.FromString,
        )
    self.qDestroy = channel.unary_unary(
        '/FTQueue/qDestroy',
        request_serializer=test__pb2.label.SerializeToString,
        response_deserializer=test__pb2.void.FromString,
        )


class FTQueueServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def qCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def qPush(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def qId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def qPop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def qTop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def qSize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def qDestroy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FTQueueServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'qCreate': grpc.unary_unary_rpc_method_handler(
          servicer.qCreate,
          request_deserializer=test__pb2.label.FromString,
          response_serializer=test__pb2.queueid.SerializeToString,
      ),
      'qPush': grpc.unary_unary_rpc_method_handler(
          servicer.qPush,
          request_deserializer=test__pb2.Push_message.FromString,
          response_serializer=test__pb2.void.SerializeToString,
      ),
      'qId': grpc.unary_unary_rpc_method_handler(
          servicer.qId,
          request_deserializer=test__pb2.label.FromString,
          response_serializer=test__pb2.queueid.SerializeToString,
      ),
      'qPop': grpc.unary_unary_rpc_method_handler(
          servicer.qPop,
          request_deserializer=test__pb2.queueid.FromString,
          response_serializer=test__pb2.Item.SerializeToString,
      ),
      'qTop': grpc.unary_unary_rpc_method_handler(
          servicer.qTop,
          request_deserializer=test__pb2.queueid.FromString,
          response_serializer=test__pb2.Item.SerializeToString,
      ),
      'qSize': grpc.unary_unary_rpc_method_handler(
          servicer.qSize,
          request_deserializer=test__pb2.queueid.FromString,
          response_serializer=test__pb2.QueLength.SerializeToString,
      ),
      'qDestroy': grpc.unary_unary_rpc_method_handler(
          servicer.qDestroy,
          request_deserializer=test__pb2.label.FromString,
          response_serializer=test__pb2.void.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FTQueue', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
