# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ntest.proto\"\x16\n\x05label\x12\r\n\x05value\x18\x01 \x01(\t\"\x15\n\x07queueid\x12\n\n\x02id\x18\x01 \x01(\x05\"/\n\x0cPush_message\x12\x10\n\x08queue_id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"\x15\n\x04Item\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\tQueLength\x12\x0e\n\x06length\x18\x01 \x01(\x05\"\x06\n\x04void\",\n\tlabel_Dis\x12\r\n\x05value\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\x05\"+\n\x0bqueueid_Dis\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08sequence\x18\x02 \x01(\x05\"E\n\x10Push_message_Dis\x12\x10\n\x08queue_id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x05\"+\n\x08Item_Dis\x12\r\n\x05value\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\x05\"1\n\rQueLength_Dis\x12\x0e\n\x06length\x18\x01 \x01(\x05\x12\x10\n\x08sequence\x18\x02 \x01(\x05\"\n\n\x08void_Dis2\xd8\x01\n\x07\x46TQueue\x12\x1d\n\x07qCreate\x12\x06.label\x1a\x08.queueid\"\x00\x12\x1f\n\x05qPush\x12\r.Push_message\x1a\x05.void\"\x00\x12\x19\n\x03qId\x12\x06.label\x1a\x08.queueid\"\x00\x12\x19\n\x04qPop\x12\x08.queueid\x1a\x05.Item\"\x00\x12\x19\n\x04qTop\x12\x08.queueid\x1a\x05.Item\"\x00\x12\x1f\n\x05qSize\x12\x08.queueid\x1a\n.QueLength\"\x00\x12\x1b\n\x08qDestroy\x12\x06.label\x1a\x05.void\"\x00\x32\xc1\x02\n\x12\x46TQueueDistributed\x12)\n\x12qCreateDistributed\x12\n.label_Dis\x1a\x05.void\"\x00\x12.\n\x10qPushDistributed\x12\x11.Push_message_Dis\x1a\x05.void\"\x00\x12%\n\x0eqIdDistributed\x12\n.label_Dis\x1a\x05.void\"\x00\x12(\n\x0fqPopDistributed\x12\x0c.queueid_Dis\x1a\x05.void\"\x00\x12(\n\x0fqTopDistributed\x12\x0c.queueid_Dis\x1a\x05.void\"\x00\x12)\n\x10qSizeDistributed\x12\x0c.queueid_Dis\x1a\x05.void\"\x00\x12*\n\x13qDestroyDistributed\x12\n.label_Dis\x1a\x05.void\"\x00\x62\x06proto3'
)




_LABEL = _descriptor.Descriptor(
  name='label',
  full_name='label',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='label.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=36,
)


_QUEUEID = _descriptor.Descriptor(
  name='queueid',
  full_name='queueid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='queueid.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=59,
)


_PUSH_MESSAGE = _descriptor.Descriptor(
  name='Push_message',
  full_name='Push_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue_id', full_name='Push_message.queue_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Push_message.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=108,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Item.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=131,
)


_QUELENGTH = _descriptor.Descriptor(
  name='QueLength',
  full_name='QueLength',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='QueLength.length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=160,
)


_VOID = _descriptor.Descriptor(
  name='void',
  full_name='void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=168,
)


_LABEL_DIS = _descriptor.Descriptor(
  name='label_Dis',
  full_name='label_Dis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='label_Dis.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='label_Dis.sequence', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=214,
)


_QUEUEID_DIS = _descriptor.Descriptor(
  name='queueid_Dis',
  full_name='queueid_Dis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='queueid_Dis.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='queueid_Dis.sequence', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=259,
)


_PUSH_MESSAGE_DIS = _descriptor.Descriptor(
  name='Push_message_Dis',
  full_name='Push_message_Dis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue_id', full_name='Push_message_Dis.queue_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Push_message_Dis.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='Push_message_Dis.sequence', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=330,
)


_ITEM_DIS = _descriptor.Descriptor(
  name='Item_Dis',
  full_name='Item_Dis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Item_Dis.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='Item_Dis.sequence', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=375,
)


_QUELENGTH_DIS = _descriptor.Descriptor(
  name='QueLength_Dis',
  full_name='QueLength_Dis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='QueLength_Dis.length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='QueLength_Dis.sequence', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=426,
)


_VOID_DIS = _descriptor.Descriptor(
  name='void_Dis',
  full_name='void_Dis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=438,
)

DESCRIPTOR.message_types_by_name['label'] = _LABEL
DESCRIPTOR.message_types_by_name['queueid'] = _QUEUEID
DESCRIPTOR.message_types_by_name['Push_message'] = _PUSH_MESSAGE
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['QueLength'] = _QUELENGTH
DESCRIPTOR.message_types_by_name['void'] = _VOID
DESCRIPTOR.message_types_by_name['label_Dis'] = _LABEL_DIS
DESCRIPTOR.message_types_by_name['queueid_Dis'] = _QUEUEID_DIS
DESCRIPTOR.message_types_by_name['Push_message_Dis'] = _PUSH_MESSAGE_DIS
DESCRIPTOR.message_types_by_name['Item_Dis'] = _ITEM_DIS
DESCRIPTOR.message_types_by_name['QueLength_Dis'] = _QUELENGTH_DIS
DESCRIPTOR.message_types_by_name['void_Dis'] = _VOID_DIS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

label = _reflection.GeneratedProtocolMessageType('label', (_message.Message,), {
  'DESCRIPTOR' : _LABEL,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:label)
  })
_sym_db.RegisterMessage(label)

queueid = _reflection.GeneratedProtocolMessageType('queueid', (_message.Message,), {
  'DESCRIPTOR' : _QUEUEID,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:queueid)
  })
_sym_db.RegisterMessage(queueid)

Push_message = _reflection.GeneratedProtocolMessageType('Push_message', (_message.Message,), {
  'DESCRIPTOR' : _PUSH_MESSAGE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:Push_message)
  })
_sym_db.RegisterMessage(Push_message)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  })
_sym_db.RegisterMessage(Item)

QueLength = _reflection.GeneratedProtocolMessageType('QueLength', (_message.Message,), {
  'DESCRIPTOR' : _QUELENGTH,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:QueLength)
  })
_sym_db.RegisterMessage(QueLength)

void = _reflection.GeneratedProtocolMessageType('void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:void)
  })
_sym_db.RegisterMessage(void)

label_Dis = _reflection.GeneratedProtocolMessageType('label_Dis', (_message.Message,), {
  'DESCRIPTOR' : _LABEL_DIS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:label_Dis)
  })
_sym_db.RegisterMessage(label_Dis)

queueid_Dis = _reflection.GeneratedProtocolMessageType('queueid_Dis', (_message.Message,), {
  'DESCRIPTOR' : _QUEUEID_DIS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:queueid_Dis)
  })
_sym_db.RegisterMessage(queueid_Dis)

Push_message_Dis = _reflection.GeneratedProtocolMessageType('Push_message_Dis', (_message.Message,), {
  'DESCRIPTOR' : _PUSH_MESSAGE_DIS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:Push_message_Dis)
  })
_sym_db.RegisterMessage(Push_message_Dis)

Item_Dis = _reflection.GeneratedProtocolMessageType('Item_Dis', (_message.Message,), {
  'DESCRIPTOR' : _ITEM_DIS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:Item_Dis)
  })
_sym_db.RegisterMessage(Item_Dis)

QueLength_Dis = _reflection.GeneratedProtocolMessageType('QueLength_Dis', (_message.Message,), {
  'DESCRIPTOR' : _QUELENGTH_DIS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:QueLength_Dis)
  })
_sym_db.RegisterMessage(QueLength_Dis)

void_Dis = _reflection.GeneratedProtocolMessageType('void_Dis', (_message.Message,), {
  'DESCRIPTOR' : _VOID_DIS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:void_Dis)
  })
_sym_db.RegisterMessage(void_Dis)



_FTQUEUE = _descriptor.ServiceDescriptor(
  name='FTQueue',
  full_name='FTQueue',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=441,
  serialized_end=657,
  methods=[
  _descriptor.MethodDescriptor(
    name='qCreate',
    full_name='FTQueue.qCreate',
    index=0,
    containing_service=None,
    input_type=_LABEL,
    output_type=_QUEUEID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qPush',
    full_name='FTQueue.qPush',
    index=1,
    containing_service=None,
    input_type=_PUSH_MESSAGE,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qId',
    full_name='FTQueue.qId',
    index=2,
    containing_service=None,
    input_type=_LABEL,
    output_type=_QUEUEID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qPop',
    full_name='FTQueue.qPop',
    index=3,
    containing_service=None,
    input_type=_QUEUEID,
    output_type=_ITEM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qTop',
    full_name='FTQueue.qTop',
    index=4,
    containing_service=None,
    input_type=_QUEUEID,
    output_type=_ITEM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qSize',
    full_name='FTQueue.qSize',
    index=5,
    containing_service=None,
    input_type=_QUEUEID,
    output_type=_QUELENGTH,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qDestroy',
    full_name='FTQueue.qDestroy',
    index=6,
    containing_service=None,
    input_type=_LABEL,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FTQUEUE)

DESCRIPTOR.services_by_name['FTQueue'] = _FTQUEUE


_FTQUEUEDISTRIBUTED = _descriptor.ServiceDescriptor(
  name='FTQueueDistributed',
  full_name='FTQueueDistributed',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=660,
  serialized_end=981,
  methods=[
  _descriptor.MethodDescriptor(
    name='qCreateDistributed',
    full_name='FTQueueDistributed.qCreateDistributed',
    index=0,
    containing_service=None,
    input_type=_LABEL_DIS,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qPushDistributed',
    full_name='FTQueueDistributed.qPushDistributed',
    index=1,
    containing_service=None,
    input_type=_PUSH_MESSAGE_DIS,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qIdDistributed',
    full_name='FTQueueDistributed.qIdDistributed',
    index=2,
    containing_service=None,
    input_type=_LABEL_DIS,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qPopDistributed',
    full_name='FTQueueDistributed.qPopDistributed',
    index=3,
    containing_service=None,
    input_type=_QUEUEID_DIS,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qTopDistributed',
    full_name='FTQueueDistributed.qTopDistributed',
    index=4,
    containing_service=None,
    input_type=_QUEUEID_DIS,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qSizeDistributed',
    full_name='FTQueueDistributed.qSizeDistributed',
    index=5,
    containing_service=None,
    input_type=_QUEUEID_DIS,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qDestroyDistributed',
    full_name='FTQueueDistributed.qDestroyDistributed',
    index=6,
    containing_service=None,
    input_type=_LABEL_DIS,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FTQUEUEDISTRIBUTED)

DESCRIPTOR.services_by_name['FTQueueDistributed'] = _FTQUEUEDISTRIBUTED

# @@protoc_insertion_point(module_scope)
